output_dir: 'output'
gpus: '0'
devices: [0, 1]
input:
    num_point_features: 4
    voxel:
        voxel_size: [0.05, 0.05, 0.1]
        point_cloud_range: [0, -40.0, -3.0, 70.4, 40.0, 1.0]
        max_num_points: 30
        max_voxels: 200
    train:
        batch_size: 4
        num_epochs: 50
        dataset:
            type: "KittiDataset"
            root_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object"
            info_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object/kitti_infos_train.pkl"
            nsweeps: 1
        preprocess:
            max_num_voxels: 40000
            shuffle: False
            num_workers: 0
            gt_location_noise: [0.25, 0.25, 0.25]
            gt_rotation_noise: [-0.15707963267, 0.15707963267]
            global_rotation_noise: [-0.78539816, 0.78539816]
            global_scale_noise: [0.95, 1.05]
            global_rotation_per_object_range: [0, 0]
            global_translation_noise: [0.2, 0.2, 0.2]
            anchor_area_threshold: -1
            remove_points_after_sample: False
            gt_drop_percentage: 0.0
            gt_drop_max_keep_points: 15
            remove_unknow_examples: False
            remove_environment: False
            db_sampler:
                enable: True
                db_info_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object/dbinfos_train.pkl"
                db_preprocess_steps:
                    filter_by_min_num_points:
                        type: "filter_by_min_num_points"
                        classes: ["Car",] 
                        values: [5,]
                    filter_by_difficulty:
                        type: "filter_by_difficulty"
                        value: [-1,]
                global_random_rotation_range_per_object: [0, 0]
                rate: 1.0
                sample_groups:
                     classes: ["Car",] 
                     values: [5, ]

    eval:
        dataset:
            type: "KittiDataset"
            root_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object"
            info_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object/kitti_infos_val.pkl"
            nsweeps: 1
        preprocess:
            max_num_voxels: 40000
            shuffle: False
            num_workers: 0
            anchor_area_threshold: -1
            remove_environment: False

box_coder:
    type: "ground_box3d_coder"
    value:
        linear_dim: False
        encode_angle_vector: False

target_assigner:
    anchor_generators:
        anchor_types: ["anchor_generator_range",]
        anchor_sizes: [[1.97, 4.63, 1.74],]
        anchor_ranges: [[-51.2, -51.2, -0.92, 51.2, 51.2, -0.92],]
        anchor_rotations: [[0, 1.57],]
        anchor_matched_thresholds: [0.6,]
        anchor_unmatched_thresholds: [0.45,]
        anchor_class_names: ["Car",]
        sample_positive_fraction: -1
        sample_size: 512
        region_similarity_calculator: 
            type: "nearest_iou_similarity"
            value: 0
model:
    encoder:
        vfe:
            type: "VoxelFeatureExtractorV3"
            num_filters: [16,]
            with_distance: False
            num_input_features: 4
        middle:
            type: "SpMiddleFHD"
            num_filters_down1: []
            num_filters_down2: []
            downsample_factor: 8
            num_input_features: 5
    decoder:
        rpn:
            type: "RPNV2"
            layer_nums: [5, 5]
            downsample_layer_strides: [1, 2]
            downsample_num_filters: [128, 256]
            upsample_layer_strides: [1, 2]
            upsample_num_filters: [128, 128]
            group_norm: False
            num_groups: 32
            num_input_features: 128
        head:
            tasks:
                num_classes: [1]
                class_names: [["car"],]
            weights: [1,]
         auxiliary:
             use_direction_classifier: True
             direction_offset: 0.785
    post_process:
        post_center_limit_range: [-51.2, -51.2, -10.0, 51.2, 51.2, 10.0]
        use_rotate_nms: True
        use_multi_class_nms: False
        nms_pre_max_size: 1000
        nms_post_max_size: 80
        nms_score_threshold: 0.1
        nms_iou_threshold: 0.2

    loss:
        loss_scale_factor: -1
        loss_norm_type: "NormByNumPositives"
        pos_class_weight: 1.0
        neg_class_weight: 2.0
        use_sigmoid_score: True
        encode_background_as_zeros: True
        encode_rad_error_by_sin: True
        classfication_loss:
            type: "weighted_sigmoid_focal"
            value: 
                alpha: 0.25
                gamma: 2.0
                anchorwise_output: True
        localization_loss:
            type: "weighted_smooth_l1"
            value: 
                sigma: 3.0
                code_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        classification_weight: 1.0
        localization_weight: 1.0
        direction_loss_weight: 0.2
