output_dir: 'output'
input:
    voxel:
        voxel_size: [0.05, 0.05, 0.1]
        point_cloud_range: [0, -40.0, -3.0, 70.4, 40.0, 1.0]
        max_num_points: 5
        max_voxels: 20000
    train:
        dataset:
            type: "KittiDataset"
box_coder:
    type: "ground_box3d_coder"
    value:
        linear_dim: False
        encode_angle_vector: False

target_assigner:
    anchor_generators:
        anchor_types: ["anchor_generator_range",]
        anchor_sizes: [(1.97, 4.63, 1.74),]
        anchor_ranges: [(-51.2, -51.2, -0.92, 51.2, 51.2, -0.92),]
        anchor_rotations: [(0, 1.57),]
        anchor_velocities: [(0, 0),]
        anchor_matched_thresholds: [0.6,]
        anchor_unmatched_thresholds: [0.45,]
        anchor_class_names: ["car",]
       
        sample_positive_fraction: -1
        sample_size: 512

        region_similarity_calculator: 
            type: "nearest_iou_similarity"
            value: 0
tasks:
    num_classes: [1,]
    class_names: [["car"],]
    

