output_dir: 'output'
gpus: '0,1'
input:
    num_point_features: 4
    voxel:
        voxel_size: [0.05, 0.05, 0.1]
        point_cloud_range: [0, -40.0, -3.0, 70.4, 40.0, 1.0]
        max_num_points: 5
        max_voxels: 20000
    train:
        dataset:
            type: "KittiDataset"
            root_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object"
            info_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object/kitti_infos_train.pkl"
            nsweeps: 1
        preprocess:
            max_num_voxels: 40000
            shuffle: False
            num_workers: 0
            gt_location_noise: [0.25, 0.25, 0.25]
            gt_rotation_noise: [-0.15707963267, 0.15707963267]
            global_rotation_noise: [-0.78539816, 0.78539816]
            global_scale_noise: [0.95, 1.05]
            global_rotation_per_object_range: [0, 0]
            global_translation_noise: [0.2, 0.2, 0.2]
            anchor_area_threshold: -1
            remove_points_after_sample: False
            gt_drop_percentage: 0.0
            gt_drop_max_keep_points: 15
            remove_unknow_examples: False
            remove_environment: False
    eval:
        dataset:
            type: "KittiDataset"
            root_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object"
            info_path: "/unsullied/sharefs/jiangzhengkai/datasets/KITTI/object/kitti_infos_val.pkl"
            nsweeps: 1
        preprocess:
            max_num_voxels: 40000
            shuffle: False
            num_workers: 0
            anchor_area_threshold: -1
            remove_environment: False

box_coder:
    type: "ground_box3d_coder"
    value:
        linear_dim: False
        encode_angle_vector: False

target_assigner:
    anchor_generators:
        anchor_types: ["anchor_generator_range",]
        anchor_sizes: [(1.97, 4.63, 1.74),]
        anchor_ranges: [(-51.2, -51.2, -0.92, 51.2, 51.2, -0.92),]
        anchor_rotations: [(0, 1.57),]
        anchor_velocities: [(0, 0),]
        anchor_matched_thresholds: [0.6,]
        anchor_unmatched_thresholds: [0.45,]
        anchor_class_names: ["car",]
        sample_positive_fraction: -1
        sample_size: 512
        region_similarity_calculator: 
            type: "nearest_iou_similarity"
            value: 0
tasks:
    num_classes: [1,]
    class_names: [["car"],]
    

